// This is a mock database of GIFs. In a real app, this would come from a CMS or API.
// Using reliable placeholder GIFs or public domain assets where possible.
// Since I cannot guarantee external hotlink stability, I am using a mix of specific generic GIFs.

export const exerciseVideoMap: Record<string, string> = {
  // Generic placeholders for demo purposes
  'default': 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExODhda3ZqZmFqZmFqZmFqZmFqZmFqZmFqZmFqZmFqZmFqZmFqZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKSjRrfIPjeiVyM/giphy.gif', // Generic workout
  
  // Specific mappings (trying to match common terms generated by AI)
  'agachamento': 'https://media.giphy.com/media/1iLzHqmJqvZ6iDrq/giphy.gif', // Squat
  'squat': 'https://media.giphy.com/media/1iLzHqmJqvZ6iDrq/giphy.gif',
  
  'flexão': 'https://media.giphy.com/media/K3Sbp8fOgKye4/giphy.gif', // Pushup
  'flexao': 'https://media.giphy.com/media/K3Sbp8fOgKye4/giphy.gif',
  'push up': 'https://media.giphy.com/media/K3Sbp8fOgKye4/giphy.gif',
  
  'supino': 'https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif', // Bench press (generic gym)
  'bench press': 'https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif',
  
  'abdominal': 'https://media.giphy.com/media/l2Je00TmqeLx0ipvq/giphy.gif', // Situp
  'crunch': 'https://media.giphy.com/media/l2Je00TmqeLx0ipvq/giphy.gif',
  
  'corrida': 'https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif', // Running
  'esteira': 'https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif',
};

export function getExerciseVideo(term: string): string {
  const normalizedTerm = term.toLowerCase();
  
  // Simple keyword matching
  for (const key in exerciseVideoMap) {
    if (normalizedTerm.includes(key)) {
      return exerciseVideoMap[key];
    }
  }
  
  return exerciseVideoMap['default'];
}
